### ISSUE TITLE
Add-on Submissions 2023

### ISSUE THREAD

**Issue by DaveBowman2001** [celestiamobile/celestia.mobi#50]
Submit your add-ons in this link below, thanks for your contribution! This is the new format introduced since 2022-Dec-28
## How to Submit an Addon through the Link?
Read the new ReadMe file on the Addon Validator here:
## For Updates to Existing Add-ons
For updates to existing add-ons, do not forget to attach the ID of the addon you want to update, and only provide details written above that needs to be updated

The id is part of the link to the add-on:
For example, this addon below has an id of A4577B17-4C60-0C1E-CAB5-92A604FF0EC3
https://celestia.mobi/resources/item?item=A4577B17-4C60-0C1E-CAB5-92A604FF0EC3

## For Removing Outdated Add-ons
In removing addons, just simply check the box labeled ```Remove this Add-on?``` and enter the ID of that addon to be removed from the official mobi list
![image](https://user-images.githubusercontent.com/95486841/210066764-2ecf494d-f16a-4c97-9283-e0d8dd5935dd.png)

## **Check Before Uploading an Add-on**

Your add-on will be running on Android/iOS/macOS/Windows, to enable maximum compatibility, please ensure that:

1. File names referenced in **models**, **ssc**, **dsc** files, etc. are exactly the same as the actual file names (some file systems are case sensitive. For example if in your .ssc there is `Mesh "Progress.cmod"`, then the file name should be exactly `Progress.cmod` not `progress.cmod`).
2. Textures should have width/height of power of 2 (for example: 1024 * 512, a texture of 1000 * 500 will not work on many mobile devices).
3. If your add-on requires specific Celestia versions, please mention in the description. Please also ensure that your add-on should not crash running on other versions.
4. If you are updating an existing add-on, note that existing users will not see an update button, so it might be a good idea to include version history in the description.
5. Please try to use smaller files for image/thumbnail/other metadata. For example, use JPG if alpha value is not needed.
6. All images need to be in JPEG (you either choose to screenshot in JPEG in Celestia or convert using tools)
7. The add-on archive should not include system files or hidden files (macOS is notorious for adding hidden system files to archives, avoid using macOS's default archive utility) this issue is found in many add-ons @Anthony-B-Russo10 uploaded
8. The add-on archive must have a flat folder structure (It should try to have fewer level of folders, do not do things like A/A/A) this issue is found in many add-ons @SpaceExplorer2008 uploaded

## Submitting Addons Without an Apple ID Account
If you have difficulties accessing the link above because of problems with your Apple ID account (or none at all), you can still submit a new addon or update an existing one by compiling them in a ZIP file in the format below. Everything with an asterisk * means it is mandatory:
```
title.txt *
description.txt *
authors.txt
release_date.txt *
last_update_date.txt
category.txt *
demo_object_name.txt *
localized_titles.json
localized_descriptions.json
addon.zip *
cover_image.jpg *
id_requirement.txt

rich_description (folder, optional, if provided, those marked * are mandatory)
- base.txt *
- notes.txt
- cover_image.jpg *
- cover_image.txt
- youtube_ids.txt
- detail_image_x.jpg
- detail_image_x.txt
- additional_leading.html
- additional_trailing.html
```
## What should be the Content of Each File Above?
BASE FILES
- **title.txt** = Title of the add-on
- **description.txt** = Plain description of the add-on, do not insert empty line between two paragraphs
- **authors.txt** = Authors, one author per line.
- **release_date.txt** = Release date in `yyyy/MM/dd HH:mm:ss` format, GMT time zone
- **last_update_date.txt** = Last update date in `yyyy/MM/dd HH:mm:ss` format, GMT time zone
- **category.txt** = Category ID, for example `https://celestia.mobi/resources/category?category=DEAF9C38-7E4B-7DFB-CA72-B496B1652550` has category ID `DEAF9C38-7E4B-7DFB-CA72-B496B1652550`. Put an empty file to indicate that the add-on needs removal
- **demo_object_name.txt** = Demo object name of the add-on
- **localized_titles.json** = Localized title in JSON format, used for non-English locale, for example `{ "zh_CN": "标题" }`
- **localized_descriptions.json** = Localized plain description in JSON format, used for non-English locale, for example` { "zh_CN": "介绍" }`
- **addon.zip** = Addon
- **cover_image.jpg** = Cover image
- **id_requirement.txt** = ID requirement for the add-on ID to start with or the add-on ID to modify if provided in full

FOR THE RICH DESCRIPTION:
- **rich_description** = Rich description folder
- **base.txt** = The first part of rich description text
- **notes.txt** = Notes, one note per line
- **cover_image.jpg** = Cover image
- **cover_image.txt** = Caption for cover image
- **youtube_ids.txt** = YouTube ID, one ID per line, for example `https://www.youtube.com/watch?v=g2ra7EdttTQ` has ID `g2ra7EdttTQ`
- **detail_image_x.jpg** = Other image, x will be replaced with number starting from 0
- **detail_image_x.txt** = Captions for other image x
- **additional_leading.html** = Raw HTML content inserted after cover image
- **additional_trailing.html** = Raw HTML content inserted at the end

Rich description will look like
```
base
NOTES:
- note 1
- note 2
cover image
cover image caption
additional leading HTML
youtube links
detail image 1
detail image caption 1
detail image 2
detail image caption 2
additional trailing HTML
```
## Additional Important Notes
- You can have links in `base.txt` and `notes.txt`, use `<a href="link">link display name</a>`.
- For add-on links, use `celaddon://item?item=ADDON_ID`, for articles use `celguide://guide?guide=GUIDE_ID` as link.
- Line breaks are ignored in `base.txt`, replace line breaks with `<br>`, replace `>` with `&gt;`, and `<` with `&lt;`
- If you're uploading a new **Exoplanet** addon, make sure you follow the [April 2022](https://celestia.space/forum/download/file.php?id=12558&filename=CelestiaExoplanets_2022_04_01.rar) catalog because the default version hasn't been updated beyond this date. Though it is still possible to follow the later versions found [here](https://celestia.space/forum/viewtopic.php?f=23&t=18705), for 100% compatibility on mobile, the April 2022 update should be followed (for now)

**Comment by levinli303** [comment]
For add-ons submitted to https://celestia.mobi/update-addon, please follow the process mentioned here https://github.com/levinli303/celestia-addon-validator

**Comment by DaveBowman2001** [comment]
Just a placeholder for my submissions on the link so that the IDs generated would not get lost in case I forget it
- **54 Piscium** = 
- **TOI-5153** = 95D0D878-D4F7-4643-913B-2D7B2AB0CF3E

**Comment by levinli303** [comment]
OK I found that there is an issue with the validator, please do not use it until further notice.

**Comment by levinli303** [comment]
Should be fixed now, please try again.

**Comment by SpaceExplorer2008** [comment]
Update **Cassini-Huygens** addon. After the default update of spacecraft body frames, the addon was updated to not generate duplicates. Also updated the model, with normal maps.

Link to download: https://drive.google.com/file/d/1biWGVVExDUNUU5duANv2rH2YFm1lIxVh/view?usp=drivesdk

**Comment by levinli303** [comment]
> Update **Cassini-Huygens** addon. After the default update of spacecraft body frames, the addon was updated to not generate duplicates. Also updated the model, with normal maps.
> 
> Link to download: https://drive.google.com/file/d/1biWGVVExDUNUU5duANv2rH2YFm1lIxVh/view?usp=drivesdk

the format is wrong. the .zip containing addon content should always be named `addon.zip`

**Comment by SpaceExplorer2008** [comment]
Fixed

**Comment by SpaceExplorer2008** [comment]
Fixed

**Comment by levinli303** [comment]
For ZIP format, one can create pull request with the zip file under `pending_zip` folder which will start a similar validation process. However GitHub does not allow uploading file directly to repositories, which means that it has to be done via git clients.

https://github.com/levinli303/celestia-addon-validator#zip-format

**Comment by Spaceforcetrump** [comment]
How can you donate money here?  Greetings from Sydney

**Comment by SpaceExplorer2008** [comment]
Now I managed to make an Apple ID, using a different email. Soon I will make new submissions of addons through the form.

**Comment by SpaceExplorer2008** [comment]
69230 Hermes: 7043A845-21A7-4DE2-8EBD-43EB81E74B38

**Comment by levinli303** [comment]
Please help test submitting with this one, https://celestia.mobi/submit-addon , it has support for automatic PR creation.

**Comment by DaveBowman2001** [comment]
> Please help test submitting with this one, https://celestia.mobi/submit-addon , it has support for automatic PR creation. after you login with both Apple ID and GitHub account

I think it's working!
https://github.com/levinli303/celestia-addon-validator/pull/45

**Comment by levinli303** [comment]
> > Please help test submitting with this one, https://celestia.mobi/submit-addon , it has support for automatic PR creation. after you login with both Apple ID and GitHub account
> 
> I think it's working! [levinli303/celestia-addon-validator#45](https://github.com/levinli303/celestia-addon-validator/pull/45)

nice. I wish I could also automate validation log posting in pull request

**Comment by DaveBowman2001** [comment]
Yesterday, I sent some 4 PRs requesting to remove some outdated addons ([example](https://github.com/levinli303/celestia-addon-validator/pull/35)). It was successfully merged, but it is still visible on the mobi list and author's list to this day

_From Exoplanets: H list_
![image](https://user-images.githubusercontent.com/95486841/210291488-754a97fe-c541-4294-9354-2e91d9f3c0c5.png)

_From SolanaBogon's list_
![image](https://user-images.githubusercontent.com/95486841/210291568-6bf7161c-4a9b-4727-8da3-6933fe39ad3f.png)

**Comment by levinli303** [comment]
> Yesterday, I sent some 4 PRs requesting to remove some outdated addons ([example](https://github.com/levinli303/celestia-addon-validator/pull/35)). All of them were successfully merged, but it is still visible on the mobi list and author's list to this day
> 
> EXAMPLE:
> 
> _From Exoplanets: H list_ ![image](https://user-images.githubusercontent.com/95486841/210291488-754a97fe-c541-4294-9354-2e91d9f3c0c5.png)
> 
> _From SolanaBogon's list_ ![image](https://user-images.githubusercontent.com/95486841/210291568-6bf7161c-4a9b-4727-8da3-6933fe39ad3f.png)

ok turned out to be a bug in OpenCloudKit, fixed. please re-submit these

**Comment by SpaceExplorer2008** [comment]
Fixed categories of the following addons:

**2018 LA**
Link to download: https://drive.google.com/file/d/1ffV7iRqR2Cb3mSGufKyJuUdef4Awobzy/view?usp=drivesdk

**Dwarf Planets Textures**
Link to download: https://drive.google.com/file/d/1fr4Kb9UHGAdzCCEI78ny-nQzocCzoJLl/view?usp=drivesdk

**Comment by levinli303** [comment]
Please test https://celestia.mobi/submit-addon which add support for zip generation and automatic PR creation

If...

Apple ID ✅ GitHub ✅ Will submit via CloudKit record, and then create PR
Apple ID ✅ GitHub ❌ Will submit via CloudKit record, record ID will be displayed
Apple ID ❌ GitHub ✅ Will submit via zip, and then create PR with zip
Apple ID ❌ GitHub ❌ Will submit via zip, zip file will be downloaded

**Comment by DaveBowman2001** [comment]
(Working)
> Apple ID ✅ GitHub ✅ Will submit via CloudKit record, and then create PR 
> Apple ID ✅ GitHub ❌ Will submit via CloudKit record, record ID will be displayed 

(Not yet Tested)
> Apple ID ❌ GitHub ✅ Will submit via zip, and then create PR with zip 
> Apple ID ❌ GitHub ❌ Will submit via zip, zip file will be downloaded

**Comment by DaveBowman2001** [comment]
I can't seem to logout my Apple ID from the addon form, I couldn't test the latter two

**Comment by DaveBowman2001** [comment]
> - Apple ID ✅ GitHub ✅ Will submit via CloudKit record, and then create PR 

OK....upon submitting two new addons ([#71](https://github.com/levinli303/celestia-addon-validator/pull/71) and [#72](https://github.com/levinli303/celestia-addon-validator/pull/72)), the validator fails somehow
![image](https://user-images.githubusercontent.com/95486841/210528717-c4ea3cd7-9638-4408-9286-bea5a5410891.png)

**Comment by DaveBowman2001** [comment]
> - Apple ID ✅ GitHub ❌ Will submit via CloudKit record, record ID will be displayed 

The generation of ID works as usual, but [manually creating PRs for them](https://github.com/levinli303/celestia-addon-validator/tree/main/pending) is now lost

**Comment by levinli303** [comment]
> I can't seem to logout my Apple ID from the addon form, I couldn't test the latter two

you can use a incognito session

> > * Apple ID ✅ GitHub ❌ Will submit via CloudKit record, record ID will be displayed
> 
> The generation of ID works as usual, but [manually creating PRs for them](https://github.com/levinli303/celestia-addon-validator/tree/main/pending) is now lost

fixed now

**Comment by DaveBowman2001** [comment]
The page for manually creating PRs still doesn't work (Page Not Found)
![image](https://user-images.githubusercontent.com/95486841/210532034-3bd773dd-820d-4721-8f3f-b3b8e6007d2a.png)

**Comment by levinli303** [comment]
> The page for manually creating PRs still doesn't work (Page Not Found)
> ![image](https://user-images.githubusercontent.com/95486841/210532626-b1975c4b-a8ef-4988-b576-c8fbad6faf2d.png)
> ![image](https://user-images.githubusercontent.com/95486841/210532034-3bd773dd-820d-4721-8f3f-b3b8e6007d2a.png)

for some reason, placeholder.txt is removed causing the directory to be gone. I added back.

**Comment by levinli303** [comment]
as whoever want to submit add-on here should already have GitHub account now. So for all normal add-ons please submit via https://celestia.mobi/submit-addon with either of the `GitHub ✅` flows. Only post here if you want customization.

**Comment by DaveBowman2001** [comment]
Seems like the new form does not automatically recognize superscripts on titles like on Psi<sup>1</sup> Draconis
Here's the customized title below:
- [Psi1 Draconis.zip](https://github.com/levinli303/celestia.mobi/files/10349127/Psi1.Draconis.zip)

**Comment by levinli303** [comment]
> Seems like the new form does not automatically recognize `<sup>`superscripts`</sup>` on titles like on the **[Psi1 Draconis](https://celestia.mobi/resources/item?item=1B45AA1C-4698-431E-89DF-1DB0D1094DE1)** addon Here's the customized title below:
> 
> * [Psi1 Draconis.zip](https://github.com/levinli303/celestia.mobi/files/10349127/Psi1.Draconis.zip)

this will not work. HTML is not supported in title. you should find special character in unicode that represent it instead of using mark-ups.

**Comment by levinli303** [comment]
Use

```
Psi¹
```

not
```
Psi<sup>1</sup>
```

**Comment by DaveBowman2001** [comment]
Ohhh ok....Titles can read unicodes but not htmls, got it

**Comment by DaveBowman2001** [comment]
## Week 2
Just a placeholder for my submissions on the link so that the IDs generated would not get lost in case I forget it and/or pull requests have failed

(PENDING)
- (NONE)

(EXOPLANETS)
(SPACECRAFT)

**Comment by SpaceExplorer2008** [comment]
Update **"M 57 (Ring Nebula)**

Link to download: https://drive.google.com/file/d/1jqfJOsUQJeWMk7V0JvwEJxx9el4Sm4SY/view?usp=drivesdk

**Comment by levinli303** [comment]
> Update **"M 57 (Ring Nebula)"** addon
> 
> Link to download: https://drive.google.com/file/d/1jqfJOsUQJeWMk7V0JvwEJxx9el4Sm4SY/view?usp=drivesdk

Submit on https://celestia.mobi/submit-addon with GitHub account logged in (Apple ID is optional now)

**Comment by SpaceExplorer2008** [comment]
I couldn't "Generate" the file, even registering the Apple ID, which I managed to create a few days ago.

**Comment by SpaceExplorer2008** [comment]
I was able to generate the ID, what do I do now?

**Comment by DaveBowman2001** [comment]
> @DaveBowman2001 Did you remove the sprite models of the Ring Nebula (M57) and Eskimo Nebula (NGC 2392)?

Yes, I did...see PRs [#49](https://github.com/levinli303/celestia-addon-validator/pull/49) and [#50](https://github.com/levinli303/celestia-addon-validator/pull/50) due to them lagging in mobile compared to jll's as reported negatively by the commenters...



> I was able to generate the ID, what do I do now? Is validation automatic or is another process required?

The validation is only automatic IF AND ONLY IF you logged in both Apple and GitHub accounts. If you're only logged in on either one of the accounts only, then you still need to copy the IDs so that a proper PR can be created, else nothing will happen

> And for new submissions, can it still be submitted without the form, just here in the issue?

I'd recommend to post any add-ons you've submitted to the form here so that I can keep track of what's the "newest" uploaded to mobi for the news articles

**Comment by SpaceExplorer2008** [comment]
> > @DaveBowman2001 Did you remove the sprite models of the Ring Nebula (M57) and Eskimo Nebula (NGC 2392)?
> 
> Yes, I did...see PRs [#49](https://github.com/levinli303/celestia-addon-validator/pull/49) and [#50](https://github.com/levinli303/celestia-addon-validator/pull/50) due to them lagging in mobile compared to jll's as reported negatively by the commenters...

Ok, but why not include them anyway? On my device they work fine. As I am having some difficulties with the submission, please include them back, I have submitted them as an alternate version.

**Comment by SpaceExplorer2008** [comment]
> The validation is only automatic IF AND ONLY IF you logged in both Apple and GitHub accounts. If you're only logged in on either one of the accounts only, then you still need to copy the IDs so that a proper PR can be created, else nothing will happen

Yes, I copied the ID. Where is it necessary to insert it?

**Comment by levinli303** [comment]
automatic PR creation and validation only requires Github account.

**Comment by levinli303** [comment]
also do not revert changes. it does not work that way.

**Comment by SpaceExplorer2008** [comment]
But I also want to know if you can still new submissions just with everything in a zip file.

**Comment by SpaceExplorer2008** [comment]
But I also want to know if it's still possible to make new addon submissions just with everything in a zip file.

**Comment by levinli303** [comment]
> But I also want to know if it's still possible to make new addon submissions just with everything in a zip file.

https://github.com/levinli303/celestia-addon-validator#zip-format

**Comment by SpaceExplorer2008** [comment]
I'm not referring to that, I'm referring to the submission made here in the issue itself, with everything in a zip file. The submission method prior to the form. It felt complicated at first, but you get used to it.

**Comment by levinli303** [comment]
> I'm not referring to that, I'm referring to the submission made here in the issue itself, with everything in a zip file. The submission method prior to the form. It felt complicated at first, but get used to it.

no

**Comment by SpaceExplorer2008** [comment]
@DaveBowman2001 Please add back the sprite models of M57 and NGC 2392, as an alternative version of jill's addon

**Comment by DaveBowman2001** [comment]
As much as possible, we shouldn't be uploading different addon versions of the same object separately. The M57 and NGC2392 models by ttcz doesn't even look anything like their real counterparts (no offense to the author, he did have some good looking models, like [NGC 6826](https://celestia.space/forum/viewtopic.php?p=153297#p153297) and [NGC 6164/6165](https://celestia.space/forum/viewtopic.php?p=153411#p153411), both of which are yet to be added to mobi). 

If only 3D modelled add-ons can be handled as easily like what `AltSurfaces` do on different versions of certain exoplanet/solar system addons, we could probably allow them co-existing in one form. But that is currently not possible, so for nebulae, spacecraft, asteroids, etc. we should only pick and post their best looking version out of many different iterations...

**Comment by DaveBowman2001** [comment]
## Week 3
Just a placeholder for my submissions on the link so that the IDs generated would not get lost in case I forget it and/or pull requests have failed

(COMETS)
- **C/2022 E3 (ZTF)**

**Comment by DaveBowman2001** [comment]
Listing all successfully submitted add-ons starting Week 7
# Week 7
(ASTEROIDS and NEOs)
- 2022 NEOs (update)

(FICTIONAL)
- Mars Rotovator

**Comment by DaveBowman2001** [comment]
## Week 12
(ASTEROIDS & NEOs)
- 99942 Apophis (update)

(EXOPLANETS)
- TOI-2285

(SPACECRAFT)
- OSIRIS-REx (update)

**Comment by DaveBowman2001** [comment]
Closing this one as addon submission tracking will now be handled by #65
